### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-python-connector#381]
See https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1177 for reference.

**Comment by enocom** [comment]
Also https://www.python.org/downloads/release/python-3130/

**Comment by enocom** [comment]
Also, we should match Cloud SQL and drop Python 3.8. See https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1176.

**Comment by jackwotherspoon** [comment]
Python 3.13 was added in asyncpg [0.30.0](https://github.com/MagicStack/asyncpg/releases/tag/v0.30.0) so once #375 is merged this should be good to go

**Comment by rhatgadkar-goog** [comment]
After #375 is merged, do we need to modify `setup.py` so that its `asyncpg` version is >= `0.30.0`?: https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/main/setup.py#L80

**Comment by jackwotherspoon** [comment]
> After #375 is merged, do we need to modify `setup.py` so that its `asyncpg` version is >= `0.30.0`?: https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/main/setup.py#L80

That is a good question and one that I have been thinking about. Since we don't pin to a specific version, if the `asyncpg` package is not already installed in the environment pip will download the latest version by default, so fresh Python 3.13 installs would get `0.30.0` automatically with our current setup.

However since we are planning to document native asyncpg pool support with the Connector #382 which was also added in `v0.30.0` then I think between the two of these it is worth pinning to `>=0.30.0` in `setup.py`.

For Cloud SQL I am going to pin to `v0.30.0` as part of adding native connection pool examples.

**Comment by rhatgadkar-goog** [comment]
I agree with you. I'll also pin to `v0.30.0` as part of adding native connection pool examples in #382

**Comment by jackwotherspoon** [comment]
Looks like this was linked to the dropping of Python 3.8 PR by accident
